### ISSUE TITLE
[Modern] Neutral bases should not have comms towers

### ISSUE THREAD

**Issue by madrabbit711** [afinegan/DynamicDCS_BugReports#10]
Neutral bases currently comms towers which are non-functional as they do not get resupply and/or give attack notifications.  Leads to wasted targeting by attack player and confusion as to what the base provides.

**Comment by Quaggles** [comment]
Is this on Bush War or Modern? I didn't notice a comms tower when attacking a neutral base on Bush War but maybe it might have been destroyed.

**Comment by madrabbit711** [comment]
Modern.  I need to check again.  Updated title.

**Comment by madrabbit711** [comment]
Haven't seen these in a while.  Can probably close this issue.
