### ISSUE TITLE
Proximity requirements need to be specified for groups of crates to be unpacked

### ISSUE THREAD

**Issue by madrabbit711** [afinegan/DynamicDCS_BugReports#11]
There is no listing of how close slung crates to spawn units, nor CC build crates, need to be to each other for successful unpacking.  More crucial during 2 x CC build crate transporting.

**Comment by Quaggles** [comment]
On the Bush War server the CC Build and CC repair crates have been merged and it only takes a single one to build a CC at a neutral base so it's not an issue there anymore, I'd imagine this will get ported to Modern when Drex has time. 

Where would this range value be listed?

**Comment by madrabbit711** [comment]
Added an additional features request discussed in Dec 2018 for in-game information page (kneeboard/briefing screen image) and/or text (F10 menu ala' BF FAQ) that possibly makes this request redundant.

#14 

Closing this ticket.
