### ISSUE TITLE
Internal crates cannot be picked up from base polygon

### ISSUE THREAD

**Issue by ddunwoody** [afinegan/DynamicDCS_BugReports#2]
Internal crates (for example JTACs and repair crates) can only be picked up from the command-centre, not from the base polygon.

This makes picking these up in a fixed-wing aircraft (especially the L-39) unnecessarily difficult.

Suggested fix: allow collection of internal crates from the base polygon as well as the command-centre if in a fixed-wing aircraft.

**Comment by Quaggles** [comment]
Was flying in the Bush War server yesterday and we could pick up internal crates from anywhere on the base, I think this feature has been added on the Bush War server but has yet to be ported to Modern.

**Comment by Quaggles** [comment]
This feature has now been ported from Bush War to modern
