### ISSUE TITLE
[Modern] L39 positions at Nalchik are unusable as they are on-top of decorative BTRs

### ISSUE THREAD

**Issue by madrabbit711** [afinegan/DynamicDCS_BugReports#8]
L39 positions at Nalchik are unusable as they are on-top of decorative BTRs.  
Current work-around: Second L39 can beused only after first spawning-in, destroying the decorative BTR (and the L39), rejoining the server to avoid craters from the previous explosions, then reselecting the second L39 position.

**Comment by Quaggles** [comment]
Fixed in DDCS Modern 3.0
